Update mvnw and CI on JDK 21
apache/netbeans-nbpackage pull request #80
Opened 2024-11-21 16:35 UTC by mbien

2024-11-21 16:54 UTC, neilcsmith-net requested changes
Thanks.  But needs the hash regenerating.

2024-11-21 16:54 UTC, neilcsmith-net commented on .mvn/wrapper/maven-wrapper.properties
> -distributionSha256Sum=83aaf914c785c9faed661f223000a92d1de9553f5c82d3b4362e66d9c031625f
Please don't remove the hash.  Will need regenerating, and `mvnw` might also need patching to pass on macOS - see https://issues.apache.org/jira/browse/MWRAPPER-150

2024-11-21 17:02 UTC, neilcsmith-net commented on .mvn/wrapper/maven-wrapper.properties
> -distributionSha256Sum=83aaf914c785c9faed661f223000a92d1de9553f5c82d3b4362e66d9c031625f
Yes, it's annoying it doesn't handle this. And that it uses sha256 so the hashes aren't published anywhere. Thanks!

2024-11-21 17:05 UTC, mbien commented on .mvn/wrapper/maven-wrapper.properties
> -distributionSha256Sum=83aaf914c785c9faed661f223000a92d1de9553f5c82d3b4362e66d9c031625f
btw do you want to keep the wrapperUrl property too? the wrapper did remove that one also.

2024-11-21 17:21 UTC, neilcsmith-net commented on .mvn/wrapper/maven-wrapper.properties
> -distributionSha256Sum=83aaf914c785c9faed661f223000a92d1de9553f5c82d3b4362e66d9c031625f
No, that's unused IIRC.  Should have removed it when I last updated this.

2025-02-27 06:44 UTC, mbien commented
did we forget to merge this? Anything what needs to be changed still?

2025-04-01 09:56 UTC, merged